### PR TITLE
Update Tests.fs

### PR DESCRIPTION
**Pull request by FoggyFinder**
added some test

### CODE REVIEW

**Comment by FoggyFinder** [comment]
Not sure if it (`LaTeX.format (arctan2 x (3Q*y)) --> """\arctan{\left(x,3y\right)}"""`) really expected result. For me it should be different.

**Comment by frabert** [comment]
I guess you mean `\arctan{\left(\frac{x}{3y}\right)}` would be a better output?

**Comment by FoggyFinder** [comment]
yeap, something like that

**Comment by frabert** [comment]
Apparently, the proper way to do it, according to [Wikipedia](https://en.wikipedia.org/wiki/Atan2), is to typeset it as `atan2`. The only problem is that we need to define a special operator in LaTeX to render it properly: https://tex.stackexchange.com/questions/313860/how-to-have-the-arctan2-atan2-function-in-latex

I am not proficient enough in LaTeX to say if there is a way to "limit the scope" of such a definition to only a formula.

**Comment by FoggyFinder** [comment]
Got it,  maybe it really the best option to do it

**Comment by frabert** [comment]
I've changed the behavior of the LaTeX formatter: now it should output `\operatorname{atan2}\left({{x}, {3y}}\right)`. You might want to update the tests to reflect this.

**Comment by frabert** [comment]
Sweet. 👍 I can merge, if you are done.

**Comment by FoggyFinder** [comment]
yeap

**Pull request merged**
